name: statuspagenv

channels:
  - conda-forge

dependencies:
  - ca-certificates=2016.2.28=0
  - click=6.6=py35_0
  - git=2.8.2=2
  - jinja2=2.8=py35_1
  - markupsafe=0.23=py35_2
  - openssl=1.0.2h=1
  - pip=8.1.2=py35_0
  - python=3.5.1=0
  - readline=6.2=2
  - setuptools=23.0.0=py35_0
  - six=1.10.0=py35_0
  - sqlite=3.9.2=0
  - tk=8.5.19=0
  - tqdm=4.7.4=py35_0
  - wheel=0.29.0=py35_0
  - xz=5.0.5=1
  - zlib=1.2.8=3
  - pip:
    - git+git://github.com/enix223/PyGithub.git@5b7f0bb6a862725102b48211d91d8a54ff992f8f
